# Generated by Django 2.1.7 on 2019-03-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="rfid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
