# Generated by Django 2.1.7 on 2019-09-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20190313_0818"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="uuid",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
