# Generated by Django 2.1.7 on 2019-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_sensor_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorrecord",
            name="value",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(default="Unnamed sensor", max_length=255),
        ),
    ]
