# Generated by Django 2.1.7 on 2019-03-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0003_auto_20190310_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
