# Generated by Django 2.1.7 on 2019-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seances", "0004_auto_20190310_0950"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seance", name="start", field=models.DateTimeField(),
        ),
    ]
