# Generated by Django 2.1.7 on 2019-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0006_seance_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
